<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\KeyInventory.Application\KeyInventory.Application.csproj" />
    <ProjectReference Include="..\..\src\KeyInventory.Domain\KeyInventory.Domain.csproj" />
    <ProjectReference Include="..\..\src\KeyInventory.Infrastructure\KeyInventory.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\KeyInventory.Web\KeyInventory.Web.csproj" />
  </ItemGroup>
</Project>
