// <auto-generated />
using System;
using KeyInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeyInventory.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KeyInventoryDbContext))]
    [Migration("20260804004500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KeyInventory.Infrastructure.Data.KeyAssetEntity", b =>
                {
                    b.Property<string>("CatalogKeyCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyTypeCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("CatalogKeyCode");

                    b.HasIndex("KeyTypeCode");

                    b.ToTable("KeyAssets", (string)null);
                });

            modelBuilder.Entity("KeyInventory.Infrastructure.Data.KeyTypeEntity", b =>
                {
                    b.Property<string>("TypeCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("TypeCode");

                    b.ToTable("KeyTypes", (string)null);
                });

            modelBuilder.Entity("KeyInventory.Infrastructure.Data.LoanEntity", b =>
                {
                    b.Property<string>("LoanCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BorrowerPartyReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CatalogKeyCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("LoanCode");

                    b.HasIndex("CatalogKeyCode");

                    b.ToTable("Loans", (string)null);
                });

            modelBuilder.Entity("KeyInventory.Infrastructure.Data.ReturnEntity", b =>
                {
                    b.Property<string>("ReturnCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LoanCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ReturnedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ReturnCode");

                    b.HasIndex("LoanCode")
                        .IsUnique();

                    b.ToTable("Returns", (string)null);
                });

            modelBuilder.Entity("KeyInventory.Infrastructure.Data.KeyAssetEntity", b =>
                {
                    b.HasOne("KeyInventory.Infrastructure.Data.KeyTypeEntity", "KeyType")
                        .WithMany()
                        .HasForeignKey("KeyTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeyType");
                });

            modelBuilder.Entity("KeyInventory.Infrastructure.Data.LoanEntity", b =>
                {
                    b.HasOne("KeyInventory.Infrastructure.Data.KeyAssetEntity", "KeyAsset")
                        .WithMany()
                        .HasForeignKey("CatalogKeyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeyAsset");
                });

            modelBuilder.Entity("KeyInventory.Infrastructure.Data.ReturnEntity", b =>
                {
                    b.HasOne("KeyInventory.Infrastructure.Data.LoanEntity", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan");
                });
#pragma warning restore 612, 618
        }
    }
}
