<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KeyInventory.Application\KeyInventory.Application.csproj" />
    <ProjectReference Include="..\KeyInventory.Infrastructure\KeyInventory.Infrastructure.csproj" />
  </ItemGroup>
</Project>
