// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace KeyControlSystem.Data.Migrations;

[DbContext(typeof(KeyControlSystemDbContext))]
[Migration("20260707224500_InitialKeyControlSchema")]
partial class InitialKeyControlSchema
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDefaultSchema("dbo")
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);
    }
}
